### ISSUE TITLE
Replace fabsf with ABS macro to avoid warnings

### ISSUE THREAD

**Issue by skela** [neilang/NAMapKit#49]
There's currently 3 warnings in this library. 2 are because of the use of fabsf which is only correct when CGFloat is an alias for floats. Because this isn't always the case (64bit/32bit) it's giving 2 warnings.

If you replace the fabsf with the ABS macro, 2 warnings go away:

	BOOL hasContentSize = fabsf(self.originalSize.width) > 0 && fabsf(self.originalSize.height) > 0;

	BOOL hasContentSize = ABS(self.originalSize.width) > 0 && ABS(self.originalSize.height) > 0;

**Comment by dblock** [comment]
Makes sense, please PR!

**Comment by skela** [comment]
I've made a pull request here https://github.com/neilang/NAMapKit/pull/50
