### ISSUE TITLE
Create Pin annotation for my swift project using NAMapkit

### ISSUE THREAD

**Issue by saravananNV** [neilang/NAMapKit#52]
This was my code
i have an image named floor_map as local image

I am very new to IOS
The pinannotation was not working but dotannotation was working perfect with same x and y co-ordinates.May be i dont know how to use this for pin annotation and also i want to show an image which replace the pin.can some one please help me.i am stuck

     let mapView: NAMapView = NAPinAnnotationMapView(frame: self.view.bounds)
        mapView.backgroundColor = UIColor.whiteColor()
        mapView.autoresizingMask = [.FlexibleWidth, .FlexibleHeight]
        mapView.minimumZoomScale = 0.5
        mapView.maximumZoomScale = 1.5
        mapView.displayMap(UIImage(named: "floor_map"))
        self.view!.addSubview(mapView)
        let melbourne: NAPinAnnotation = NAPinAnnotation()
        melbourne.color = NAPinColorPurple
        melbourne.title = "Melbourne"
        melbourne.subtitle = "I have a subtitle"
        melbourne.point = CGPoint(x: 543.0, y: 450.0)
        mapView.addAnnotation(melbourne, animated: false)

**Comment by dblock** [comment]
IMO it should "just work", maybe put together a dummy project that shows the issue?

**Comment by saravananNV** [comment]
Ofcourse, I have seen the demo project and use the code form the file NAPinAnnotationsDemoViewController which was used to creae pin..the only difference was i converted into swift..but my effort was in vain

**Comment by dblock** [comment]
@saravananNV Put your project on Github, open an issue and link from here. Me or someone else will take a look when we get a chance. Maybe you'll get a PR with a fix ;)

**Comment by saravananNV** [comment]
@dblock  ..thank u..here is the git hub link of the project 

https://github.com/saravananNV/NaMapkit

Thanks Guys,

**Comment by orta** [comment]
could be because the pin assets are inside a separate bundle now, and they may have been using `UIImage imageNamed:`

**Comment by saravananNV** [comment]
Hi Orta,
I have given my git hub project link above which use NAMapkit frame work. can you please see that and tell me where i am wrong.

 Help will be appreciated

Thanks Guys

**Comment by dblock** [comment]
I put a breakpoint in the loading of the image in https://github.com/neilang/NAMapKit/blob/master/NAMapKit/NAPinAnnotationView.m#L56, and that's exactly the problem, the image isn't loaded from the bundle.

```objc
    UIImage *pinImage = [UIImage imageWithContentsOfFile:[[[NSBundle mainBundle] bundlePath] stringByAppendingString:pinImageName]];
    [self setImage:pinImage forState:UIControlStateNormal];
```

This ends up being something like "/Users/dblock/Library/Developer/CoreSimulator/Devices/6171C10F-67C0-471D-B74B-7E4149ACDF69/data/Containers/Bundle/Application/A14D79BC-8942-407D-B9B3-C6D4E2D24639/sample.app/pin_purple.png" which is incorrect, it's missing "Frameworks/NAMapKit.framework" in the path.

@orta Do you know the right way to fix this?

**Comment by orta** [comment]
`[NSBundle mainBundle] bundlePath]` wants to changes for `[NSBundle mainBundle] bundleForClass:NSMapKit.class]`

**Comment by dblock** [comment]
@saravananNV Want to try to fix this in this project and submit a pull request?

**Comment by saravananNV** [comment]
Is there is any way to fix this bug?.. or you guys working on it.i have to use this wonderful mapkit in our project with in two days.thats y , i am making it to work on this sample app for a trial..

Thanks

**Comment by dblock** [comment]
Fix the bug by changing the code in NAMapKit as orta suggests above.
Submit a pull request with the fix after you've tested it.

**Comment by saravananNV** [comment]
when i try to change that particular line.it shows the below error:

  No visible @interface for 'NSBundle' declares the selector 'bundleForClass:'

**Comment by orta** [comment]
@saravananNV - https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/index.html#//apple_ref/occ/clm/NSBundle/bundleForClass:

**Comment by saravananNV** [comment]
I put these lines  on NAPinAnnotationView.m..but it shows undeclared identifier NAMapkit

 NSBundle *bundle = [NSBundle bundleForClass:NAMapKit.class];
    UIImage *pinImage = [UIImage imageWithContentsOfFile:[[bundle stringByAppendingString:pinImageName]];

can u please put the sample code for worki with pin annotation..i am running out of time.

Thanks orta & dblock

**Comment by saravananNV** [comment]
is there is any way to use images for dot annotations.so i can leave pin and continue work with dot annotations

**Comment by saravananNV** [comment]
Hi Orta & dblock,

  Can you please tell a solution how to fix the problem.i change the line on the mentioned file on NAMapkit file..but the pinannotation view was not working..Guys, can you please help me with piannotation.

**Comment by saran-metron** [comment]
HI Orta &  dblock

hey, guys i fxed it....i modified the line on https://github.com/neilang/NAMapKit/blob/master/NAMapKit/NAPinAnnotationView.m#L56
by

 NSString * image = _animating ? [NSString stringWithFormat:@"%@Floating", pinImageName] : pinImageName;
    [self setImage:[UIImage imageNamed:image] forState:UIControlStateNormal];

**Comment by saravananNV** [comment]
HI Orta &  dblock

hey, guys i fxed it....i modified the line on https://github.com/neilang/NAMapKit/blob/master/NAMapKit/NAPinAnnotationView.m#L56
by

 NSString * image = _animating ? [NSString stringWithFormat:@"%@Floating", pinImageName] : pinImageName;
    [self setImage:[UIImage imageNamed:image] forState:UIControlStateNormal];

which is from 
https://github.com/nicked/NAMapKit/blob/master/NAMapKit/NAPinAnnotationView.m
line 58

**Comment by saravananNV** [comment]
Hi,

 i want to move pinannotation one location to another how to acheive it.can you guys suggest some ideas

**Comment by orta** [comment]
@saravananNV - I'm afraid I don't have the time to hold your hand through using this library.

**Comment by saravananNV** [comment]
@orta ,
 you and @dblock  have spend your valuable time with me.
  all my issues are fixed..last task was how can i change images for pin annotation.just give me a lead.then i will work on it.sorry to disturb u @orta 

thanks

**Comment by dblock** [comment]
I think if you want to change the images you might want to either subclass the annotation class or roll out your own.

**Comment by dblock** [comment]
Would appreciate a pull request with your fix, please @saravananNV.

**Comment by saravananNV** [comment]
hoe to make the pull request @dblock

**Comment by saran-metron** [comment]
@dblock  and @orta  there is no image porperty on Annotation class.then how can i change the image instead of pin

**Comment by saravananNV** [comment]
@dblock  and @orta i have created a custom class which inherits the annotation and override the function createviewonmapview.but how to integrate this function which explicit my new view and also how to set image for customized pin. i know that i am troubling you too. i am stuck.thats y..please help me

thanks,

**Comment by dblock** [comment]
@saran-metron and @saravananNV - you're not getting much help here because you're asking for fairly basic things, and I totally understand that you're just starting programming in Objective-C, but people contributing to this project don't really have time to teach you the basics. I suggest finding a friend or colleague who's a bit more experienced and pairing with them on this. I am sorry I cannot be of much more help - when/if I have time I'll write up some more examples.

**Comment by dblock** [comment]
Fixed via https://github.com/neilang/NAMapKit/commit/ce7ed0797c7b41056d01aa1390026874e7421b0a.
