### ISSUE TITLE
 minimize the map view once the page loaded

### ISSUE THREAD

**Issue by saran-metron** [neilang/NAMapKit#53]
how to minimize the map view .i want to make the minimize the zoom level of map when the view was loaded

**Comment by dblock** [comment]
Are you looking for `setZoomScale`?

Here's how the map zooms to fit: https://github.com/neilang/NAMapKit/blob/dd8ab2134aec272d61dfa3a33832da98a6d988d1/NAMapKit/NATiledImageMapView.m#L80?

```objc
- (void)zoomToFit:(BOOL)animate
{
    [self setZoomScale:self.minimumZoomScale animated:animate];
}
```

**Comment by orta** [comment]
Closing due to lack of a response, and this seems like the right answer.
