### ISSUE TITLE
Custom annotation images

### ISSUE THREAD

**Issue by nicked** [neilang/NAMapKit#8]
Allow a custom image instead of the pin.

**Comment by saran-metron** [comment]
@nicked  if u have sample project for customizing the pin with images..can you please share ti here.it is really helpful for me
thanks
saran

**Comment by saravananNV** [comment]
@nicked can u please help me to tell how to overwrite NAAnnotaion to customize pin images with our own.i am stuck. i am new to ios.so please help me

**Comment by saran-metron** [comment]
@nicked can u tell how to overwrite the annotation class and cutomize pin images.

**Comment by orta** [comment]
@saravananNV and @nicked - please be respectful of time of others on this project, you've started to become spammers on this repo and I don't want to resort to using the blocking tools because it can cut you off from documentation.
